articles/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index),
    path('new/', views.new),
    path('create/', views.create),
    path('<int:article_pk>/', views.detail),
    path('<int:article_pk>/delete/', views.delete),
    path('<int:article_pk>/edit/', views.edit),
    path('<int:article_pk>/update/', views.update),
]

jobs/urls.py
from django.urls import path
from . import views

app_name = 'jobs'

urlpatterns = [
    path('', views.index, name='index'),
    path('result/', views.result, name='result')    
]

reboot/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('articles/', include('articles.urls')),
    path('jobs/', include('jobs.urls')),
]

articles/models.py
from django.db import models

# Create your models here.
class Article(models.Model):
    title = models.CharField(max_length=10)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

jobs/models.py
from django.db import models

# Create your models here.
class PastLife(models.Model):
    name = models.CharField(max_length=10)
    job = models.CharField(max_length=30)

articles/views.py
from django.shortcuts import render, redirect
from .models import Article


# Create your views here.
def index(request):
    articles = Article.objects.all()
    context = {
        'articles': articles
    }
    return render(request, 'articles/index.html', context)

def new(request):
    return render(request, 'articles/new.html')

def create(request):
    article = Article()
    article.title = request.POST.get('title')
    article.content = request.POST.get('content')
    article.save()
    return redirect('/articles/')
    # return render(request, 'articles/create.html')
    
def detail(request, article_pk):
    article = Article.objects.get(pk=article_pk)
    context = {
        'article': article
    }
    return render(request, 'articles/detail.html', context)

def delete(request, article_pk):
    article = Article.objects.get(pk=article_pk)
    article.delete()
    return redirect('/articles/')

def edit(request, article_pk):
    article = Article.objects.get(pk=article_pk)
    context = {
        'article': article
    }
    return render(request, 'articles/edit.html', context)

def update(request, article_pk):
    article = Article.objects.get(pk=article_pk)
    article.title = request.POST.get('title')
    article.content = request.POST.get('content')
    article.save()
    return redirect(f'/articles/{article_pk}/')

jobs/views.py
import requests
from decouple import config
from faker import Faker
from IPython import embed
from django.shortcuts import render
from .models import PastLife
# Create your views here.

def index(request):
    return render(request, 'jobs/index.html')

def result(request):
    name = request.GET.get('name')
    # DB에 이름이 있으면,
    past_life = PastLife.objects.filter(name=name).first()
    if not past_life:
        # 이름이 없으면, 
        fake = Faker()
        job = fake.job()
        past_life = PastLife.objects.create(name=name, job=job)
    # 직업 결과에 따라, giphy 요청
    job = past_life.job
    api_key = config('GIPHY_API_KEY')
    # 1. url 설정
    url = f'http://api.giphy.com/v1/gifs/search?api_key={api_key}&q={job}&lang=en'
    # 2. 요청 보내기
    response = requests.get(url).json()
    print(response)
    # 3. 응답 결과에서 이미지 url 뽑기
    try:
        image_url = response['data'][0].get('images').get('original').get('url')
    except:
        image_url = None
    context = {
        'past_life': past_life,
        'image_url': image_url
    }
    return render(request, 'jobs/result.html', context)

articles/templates/articles/detail.html
{% extends 'base.html' %}

{% block body %}
<h1>{{ article.pk }}</h1>
<h2>{{ article.title }}</h2>
<p>{{ article.content }}</p>
<p>{{ article.created_at }}</p>
<p>{{ article.updated_at }}</p>
<a href="/articles/{{article.pk}}/delete/">삭제</a>
<a href="/articles/{{article.pk}}/edit/">수정</a>
{% endblock %}

articles/templates/articles/edit.html
{% extends 'base.html' %}

{% block body %}
<form action="/articles/{{article.pk}}/update/" method="POST">
    {% csrf_token %}
    <label for="title">제목 : </label>
    <input type="text" id="title" name="title" value="{{article.title}}">
    <label for="content">내용 : </label>
    <textarea name="content" id="content" cols="30" rows="10">{{article.content}}</textarea>
    <input type="submit" value="제출!">
</form>
{% endblock %}

articles/templates/articles/index.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    <h1>안녕!</h1>
    <a href="/articles/new">글 작성하기</a>
    {% for article in articles %}
        <p>{{ article.id }}</p>
        <p>{{ article.title }}</p>
        <a href="/articles/{{article.pk}}/">글 보기</a>
        <hr>
    {% endfor %}
</body>
</html>

articles/templates/articles/new.html
{% extends 'base.html' %}

{% block body %}
<form action="/articles/create/" method="POST">
    {% csrf_token %}
    <label for="title">제목 : </label>
    <input type="text" id="title" name="title">
    <label for="content">내용 : </label>
    <textarea name="content" id="content" cols="30" rows="10"></textarea>
    <input type="submit" value="제출!">
</form>
{% endblock %}

articles/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    {% block body %}
    {% endblock %}
</body>
</html>

jobs/templates/jobs/index.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    <h1>당신의 전생은</h1>
    <form action="{% url 'jobs:result' %}">
        <label for="name">이름</label>
        <input type="text" id="name" placeholder="이름을 입력하세요" name="name">
        <input type="submit" value="제출">
    </form>
</body>
</html>

jobs/templates/jobs/result.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    <h1>결과!</h1>
    <h2>{{ past_life.name }}님은 전생에 {{ past_life.job }}</h2>
    <img src="{{ image_url}}" alt="{{ past_life.job }}">
</body>
</html>